spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

---

spring:
  config:
    activate:
      on-profile: prod

decorator:
  datasource:
    p6spy:
      enable-logging: false

---

spring:
  config:
    activate:
      on-profile: local


decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j