spring:
  config:
    activate:
      on-profile: prod

  output:
    ansi:
      enabled: always

decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: true
      logging: slf4j