spring:
  profiles:
    group:
      local: local, datasource
      prod: prod, datasource

  # Spring Security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID} # idToken.aud에 해당
        provider:
          kakao:
            issuer-uri: "https://kauth.kakao.com"
            jwk-set-uri: "https://kauth.kakao.com/.well-known/jwks.json"


app:
  jwt:
    issuer: "api.goforawalk.site"
    user-name-attribute: "sub"
    at-secret-key: ${JWT_AT_SECRET_KEY}
    rt-secret-key: ${JWT_RT_SECRET_KEY}
    at-expiration-seconds: ${JWT_AT_EXPIRATION_SECONDS}
    rt-expiration-seconds: ${JWT_RT_EXPIRATION_SECONDS}

