spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_URL}

decorator:
  datasource:
    p6spy:
      enable-logging: false

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j