# docker-compose.yml (원격 인스턴스용)
version: "3.8"

services:
  app-server: # 서비스 이름
    build: # 빌드 설정
      context: .
      dockerfile: Dockerfile
    image: app-server:latest # 로컬에서 빌드될 이미지 이름과 태그
    container_name: app-server-container # 실행될 컨테이너 이름
    restart: always # 컨테이너 재시작 정책
    ports:
      - "8080:8080" # 호스트 포트:컨테이너 포트
    environment:
      - SPRING_PROFILES_ACTIVE=prod # 실행 환경 프로필
      # 필요한 다른 환경 변수 추가
    volumes: # 런타임에 필요한 볼륨 설정
      - ./upload:/app/upload # 예시: 호스트의 ./upload 디렉토리를 컨테이너 내부 /app/upload와 연결